### ISSUE TITLE
Erroneous <pre> tag in rendered output

### ISSUE THREAD

**Issue by thebadmonkeydev** [gjtorikian/graphql-docs#23]
I'm getting erroneous `<pre>` tags in the output of field descriptions and interface lists. I've been able to reproduce this by making a clean clone and running `bundle exec rake sample`

![screenshot1](https://user-images.githubusercontent.com/6217672/26846936-4985c23a-4ac9-11e7-8018-1d17df44f772.png)

Notice in the screenshot how the `a`, `code`, and `li` tags are all clobbered by surrounding `<pre>` and `<code>` tags:

![screenshot2](https://user-images.githubusercontent.com/6217672/26847001-858f9d3c-4ac9-11e7-92ab-09f49a8d6905.png)

**Comment by gjtorikian** [comment]
Ahhhhh, sorry! I'll fix this ASAP.

**Comment by thebadmonkeydev** [comment]
@gjtorikian Nice! Unfortunately, it looks like there was another culprit as well. You fixed the example above, but there's also this example found with 0.6.1:

![screenshot from 2017-06-06 23-50-16](https://user-images.githubusercontent.com/6217672/26861644-2c4d8ad2-4b13-11e7-95b8-8e8ff2333079.png)

![screenshot4](https://user-images.githubusercontent.com/6217672/26861648-33dfc7ba-4b13-11e7-9d36-3a903fb09c43.png)

**Comment by gjtorikian** [comment]
_Ugh._ Sorry for the trouble. 0.6.2 should take care of this.
