### ISSUE TITLE
How to generate schema content?

### ISSUE THREAD

**Issue by Mori** [gjtorikian/graphql-docs#32]
From the Readme:

    GraphQLDocs.build(schema: contents)

How do I generate `contents`? Should this work?

    > GraphQLDocs.build(schema: GraphQL::Schema::Printer.print_schema(MySchema))
    GraphQL::ParseError: Parse error on "}" (RCURLY) at [1468, 1]                                             
    from parser.y:442:in `on_error'                                                                          

but then maybe something in MySchema is broken? Is this diagnostic?

    > GraphQL.parse(GraphQL::Schema::Printer.print_schema(MySchema))    
    GraphQL::ParseError: Parse error on "}" (RCURLY) at [1468, 1]                                      
    from parser.y:442:in `on_error'                                                                    

MySchema is working fine for generating query results. Can it work for queries but still be broken for parsing? How would I go about debugging that? Or am I generating the contents incorrectly?

Thanks ...

**Comment by gjtorikian** [comment]
Yeah, `schema: contents` should be the IDL string that is generated by `GraphQL::Schema::Printer.print_schema`. Is ` GraphQL::Schema::Printer.print_schema(MySchema)` generating an IDL file for you? What is its output?

**Comment by Mori** [comment]
@gjtorikian, I just commented out everything but the base query type, but I'm still getting the same error:

```
> GraphQL::Schema::Printer.print_schema(MySchema)                
=> "type Query {\n\n}"                                                                         
> GraphQLDocs.build(schema: "type Query {}")                       
GraphQL::ParseError: Parse error on "}" (RCURLY) at [1, 13]                                    
from parser.y:442:in `on_error'                                                                
> GraphQL::Schema::Printer.print_schema(MySchema)                
=> "type Query {\n\n}"                                                                         
> GraphQL.parse(GraphQL::Schema::Printer.print_schema(MySchema)) 
GraphQL::ParseError: Parse error on "}" (RCURLY) at [3, 1]                                     
from parser.y:442:in `on_error'                                                                
> GraphQL.parse("type Query {\n\n}")                               
GraphQL::ParseError: Parse error on "}" (RCURLY) at [3, 1]                                     
from parser.y:442:in `on_error'                                                                
> GraphQL.parse("type Query {}")                                   
GraphQL::ParseError: Parse error on "}" (RCURLY) at [1, 13]                                    
from parser.y:442:in `on_error'                                                                
> GraphQLDocs.build(schema: "type Query {}")                       
GraphQL::ParseError: Parse error on "}" (RCURLY) at [1, 13]                                    
from parser.y:442:in `on_error'   
```                                                             

Is `type Query {}` a valid schema string? Do you expect this to work?

I'm using: rails 3.2.22.4, ruby 1.1.7, graphql 1.7.6, graphql-docs 1.0.0

Thanks ...

**Comment by rmosolgo** [comment]
> Is `type Query {}` a valid schema string?

It looks like graphql-ruby doesn't support this: 

https://github.com/facebook/graphql/pull/90/files#r132484441

(but maybe it should)

**Comment by gjtorikian** [comment]
I can toss a PR your way @rmosolgo. It would appear that graphql-ruby emits `{}` into the IDL but isn't properly printing it.

Thanks for the report, @Mori !

**Comment by Mori** [comment]
@gjtorikian, @rmosolgo: I confirmed that empty `{}` blocks inside of the schema were my problem. Within the schema I had

   type Mutation {
    }   
    
and

    interface Viewable {
    } 

They were left empty as placeholders for future work. When I either remove these types or add a field to them, the printed schema can be successfully parsed and `GraphQLDocs.build` can do its magic.

Thanks, and thank you for your great work on these gems!
