### ISSUE TITLE
graphql-docs doesn't generate Mutation listing 

### ISSUE THREAD

**Issue by joetempleman** [gjtorikian/graphql-docs#46]
For some reason when using graphql-docs I can't get it to generate the mutation listing properly. 

I discovered it when I couldn't get it to work properly for our own schema but even when running `bundle exec rake sample` the mutation landing page is blank even though the Query page lists the correct queries and the site hosted at https://www.gjtorikian.com/graphql-docs/object/mutation/ lists them correctly. 

Is this a bug or am I doing something wrong?

**Comment by gjtorikian** [comment]
Could you provide some code showing how it's being run, or your schema?

**Comment by tobespangler-bic** [comment]
We are seeing the same thing in our project. 

The mutations themselves are all visible in the `mutation` section of the generated doc but the page the mutation link under the `queries` section goes to is effectively empty. 

@joetempleman did you find a resolution?

**Comment by gjtorikian** [comment]
Is your schema available publicly? Using that would help me generate a test case.

**Comment by bobbybobby** [comment]
I have the same issue. Here is a small demo app I made to reproduce the problem : https://github.com/bobbybobby/demo-graphql-doc-bug

**Comment by gjtorikian** [comment]
> I have the same issue. Here is a small demo app I made to reproduce the problem : https://github.com/bobbybobby/demo-graphql-doc-bug

Thanks! This is super helpful for testing.

**Comment by gjtorikian** [comment]
I believe this was handled in https://github.com/gjtorikian/graphql-docs/pull/55, to be released soon.

**Comment by bbugh** [comment]
Hi 👋

I just installed the gem (1.8.0) and am still seeing this issue. Our top level objects are the defaults (Mutation), so it seems like #55 is unrelated. As in the original report, our Mutations page is not showing the listings, but they do appear in the sidebar.

**Comment by gjtorikian** [comment]
@bbugh Would you happen to have a public schema handy so that I can investigate?

**Comment by bbugh** [comment]
@gjtorikian Thanks for the reply! 

It actually hasn't worked on any schema I've tried it on, either ours, random public ones, or hand-written test ones. Here's a public one where it doesn't work https://github.com/marmelab/GraphQL-example/blob/master/schema.graphql

Here's a simple test where it doesn't work:

```graphql
type Query {
  someString: String
}

type Mutation {
  testMutation(anything: String!): String
}
```

I'm running it like this:

```ruby
require 'graphql-docs'
GraphQLDocs.build(filename: 'schema.graphql')
```

**Comment by gjtorikian** [comment]
@bbugh Sorry, but even with [that schema you provided](https://github.com/gjtorikian/graphql-docs/compare/broken-mutations?expand=1), the tests [continue to pass](https://travis-ci.org/gjtorikian/graphql-docs/builds/545902098?utm_source=github_status&utm_medium=notification). Is there anything else about your setup that might be different?

**Comment by stephentuso** [comment]
@gjtorikian Hey, it seems like this is happening again, you can see it on [the example mutations page](https://www.gjtorikian.com/graphql-docs/operation/mutation/)

**Comment by gjtorikian** [comment]
That page is supposed to look like that -- it's [this generic landing page](https://github.com/gjtorikian/graphql-docs/blob/d59d91b91216395bbbe707140bc24edf1c51dd14/lib/graphql-docs/landing_pages/mutation.md).

**Comment by stephentuso** [comment]
Based on the comments above I thought that wasn't right - [Query](https://www.gjtorikian.com/graphql-docs/operation/query/) has a landing page too but it lists all the fields beneath it, with none in the sidebar. It seems weird for the root types to have different layouts
