### ISSUE TITLE
Whitespace formatting removed from schema during parser initialization

### ISSUE THREAD

**Issue by tobespangler-bic** [gjtorikian/graphql-docs#47]
When creating a parser during document creation using our schema the initialization strips away whitespace formatting in our descriptions.

I think it's the Graphql-ruby gem doing from_definition
```ruby
@schema = GraphQL::Schema.from_definition(schema)
```

This is an issue as we are trying to add formatted code blocks to our descriptions and this step is removing all of our leading whitespace within the block. As a hack we are overwriting with our original
schema 
```ruby
parser.instance_variable_set(:@schema, PlatformVsArenaSchema)
```` 
before calling 
```ruby
parser.parse
```

If open to supporting having the parser take a graphql::schema object in some manner I can work on some ideas and make a PR?

**Comment by gjtorikian** [comment]
Is this schema public by any chance, so I can examine it and try and write test coverage around it?

If it _is_ happening from the `graphql-ruby` gem then I'm not sure anything can be done here and the issue should probably be opened [over there](https://github.com/rmosolgo/graphql-ruby).

**Comment by tobespangler-bic** [comment]
Unfortunately our schema isn't public no.

In my testing (snippet blow) I could see leading whitespace in the string being passed in (created using GraphQL::Schema.to_definition) but none left after the GraphQL::Schema.from_definition call. It definitely looked like it was in the graphql-ruby code. I will open something up over there as you suggest.

For your project I was wondering about allowing us to skip the conversion from the string into a schema object by allowing the parser to take a pre-created GraphQL::Schema object (aka one from GraphQL::Schema.define) as opposed to a string.

To test I was using something like the following ... anything to generate some leading whitespace in a description string.

```ruby
Schema = GraphQL::Schema.define do
  query(Types::QueryType)
end

Types::QueryType = GraphQL::ObjectType.define do
  name 'Query'

  field :test do
    type types.Int
    description "Title paragraph.
    ```
    line1
      line2
    line3
    ```"
  end
```
