### ISSUE TITLE
Sidebar as separate file?

### ISSUE THREAD

**Issue by piotrze** [gjtorikian/graphql-docs#48]
Is there a way to generate sidebar as separate file?

I've tried to use erb markups in landing pages in order to generate list of items, but with no luck.

**Comment by gjtorikian** [comment]
It is, but admittedly, it's not very intuitive. It depends entirely on how your build process is set up. For example, https://developer.github.com/v4/ uses this gem, but it applies its own styles -- this gem just handles the parsing. 

First, you'll need to set the `use_default_styles` option to `false`. You'll likely want to change all of the landing pages to custom landing pages, too.

Then, you'll have to call the various stages individually (I think this is the only piece of information actually documented):

``` ruby
response = File.read(options[:filename])

parser = GraphQLDocs::Parser.new(response, options)
parsed_schema = parser.parse

generator = GraphQLDocs::Generator.new(parsed_schema, options)
```

Now, `generator` contains a giant blob of all the objects and operations and whatnot from your schema. At this point you'll need to iterate over it and apply your custom layouts (with your custom sidebar).

Does that make sense? I'm definitely up for suggestions on improving the process or documentation.
