### ISSUE TITLE
"*** No sourcefile available for (erb)" error when attempting to customize template

### ISSUE THREAD

**Issue by Mori** [gjtorikian/graphql-docs#50]
I'm attempting to customize the `objects` template (to add an "Examples" section). To do this I made a copy of the graphql_objects.html file in my project, and then tried:

    GraphQLDocs.build(
       ...
       templates: { objects:  OBJECT_TEMPLATE_PATH.to_s },
       ...
    }

...where `OBJECT_TEMPLATE_PATH` points to my local copy of the objects template. Since that fails and seems to erase the other templates as well, I tried this instead:

    opts = GraphQLDocs::Configuration::GRAPHQLDOCS_DEFAULTS 
    GraphQLDocs.build(
       ...
       templates: opts[:templates].merge(objects: OBJECT_TEMPLATE_PATH.to_s),
       ...
    }

I've confirmed that the local template file is readable. But when I execute this I get this error:

      *** No sourcefile available for (erb)  

It is raised on [this line](https://github.com/gjtorikian/graphql-docs/blob/9d3ab872dc43913afc98ac4ebe4e2308436bcf99/lib/graphql-docs/generator.rb#L110) of `GraphQLDocs::Generator#create_graphql_object_pages`. Tracing it into ERB, the error occurs on line 850 of erb.rb:

     eval(@src, b, (@filename || '(erb)'), 0)  

This not a normal Ruby error, in that it cannot be trapped in a `rescue` block.

It appears that the only difference between a working configuration and one that fails with this error is that the failing version points to a local project copy of that template file, rather than the copy in the gem.

Am I setting the `opts[:templates][:objects]` key incorrectly?

Any suggestions appreciated. Thanks for this very useful gem.

**Comment by gjtorikian** [comment]
> Am I setting the opts[:templates][:objects] key incorrectly?

It doesn't look like you are; I also can't reproduce this result. 

I'm going to push a quick bug fix to do two things:

* When setting a single key `templates[:options]`, don't blow up all the other values
* Perform a `File.read` on the templates before attempting to use them

I don't think this'll fix the problem entirely but maybe the second change will give a clue on why the template is not rendering.

**Comment by gjtorikian** [comment]
Ok, change 1.4.1 should have some more debugging/complaints around template reading. Note that now you can actually do:

``` ruby
GraphQLDocs.build(
   ...
   templates: { objects:  OBJECT_TEMPLATE_PATH.to_s },
   ...
}
```

and not have every template overwritten. Could you let me know if you still get an error?

**Comment by Mori** [comment]
1.4.1 works! No errors. I don't know where that strange erb error went, but it went. Thank you Garen.
