### ISSUE TITLE
Support relative urls by default

### ISSUE THREAD

**Issue by emilebosch** [gjtorikian/graphql-docs#62]
Thanks for making this! I was wondering shall we make it possible to support relative urls by default ? Right now if I generate in a directory it is looks pretty bad because it uses / in front of its urls.

Yard uses relative urls and there forsakes it easy to put docs in in a separate folder. i.e docs/graphql

**Comment by gjtorikian** [comment]
In my experience with differences in local/production generation,  I went with how Jekyll serves content, ie. with a `base_url` set. So in the hash option if you want to store the content elsewhere you can set `base_url: docs/graphql`.

**Comment by amkisko** [comment]
@gjtorikian it does not work for generated docs in CI, e.g. when you store docs in GitLab/GitHub Artifacts. When I set base_url to ".", then it breaks on subfolders, also links does not include index.html, navigation is not working. Generator does not respect relations of pages.
