### ISSUE TITLE
Landing pages as ERB templates

### ISSUE THREAD

**Issue by ff-sushild** [gjtorikian/graphql-docs#63]
Is there any way to use erb templates for landing pages instead of plain markdown files? Would like to localize the static text but not seeing any obvious way.

**Comment by gjtorikian** [comment]
Hmm, there isn't at the moment. Seems like something that should be added, but just so I understand the use case, how would you expect to provide the variables necessary to build alongside the ERB template?

**Comment by ff-sushild** [comment]
Thanks for the replying and building such a awesome gem. Variables can be passed as options  parameters (context variable or somethings similar).  I was able to render as ERB by tweaking this line https://github.com/gjtorikian/graphql-docs/blob/master/lib/graphql-docs/generator.rb#L30 but not able to decide where to send the binding. Let me know if I am overlooking renderer docs or wiki.
