### ISSUE TITLE
Support for quote-styled comment

### ISSUE THREAD

**Issue by thrieu** [gjtorikian/graphql-docs#64]
When parsing content with quote-styled comment such as `"""The ID of user"""` , it throws an error 
` Parse error on "id" (IDENTIFIER) at [9, 3] (GraphQL::ParseError)`

It is possible to support that?

**Comment by gjtorikian** [comment]
Wild -- out of curiosity, is this coming from the IDL file? Could you post that snippet?

**Comment by thrieu** [comment]
Hi @gjtorikian , The following snippet is generated by https://github.com/graphql-cli/graphql-cli
```graphql
type Query {
  profile: User
}

"""
A user
"""
type User {
  """
  The id of the user
  """
  id: String!

  """
  The email of user
  """
  email: String
}
```

**Comment by jregistr** [comment]
Any news on this getting implemented?
