### ISSUE TITLE
Feature: Rendering/Listing directives on a field/type/etc

### ISSUE THREAD

**Issue by jtaylor10** [gjtorikian/graphql-docs#69]
Tool supports rendering deprecation notices based on the `@deprecated` directive. It would be nice to support other directives. An example specific to one of our projects: we have a `@authorize(scope: 'some-scope')` custom directive that does some up front authorization and it would great if the docs could render something alongside the fields annotated with this. 

Haven't spent enough time looking at this code to truly see if this is quick and easy and I'm not sure if there is a simple solution. For documentation purposes, each directive can have documentation on it like all other items get so you could have a side-panel section called `Directives` that lists the directives they'll encounter with a description of what each means.  Then each field that is annotated with a directive could just link to the appropriate page for details and print the directive as it's found in the schema maybe?  

Open to ideas as to how to resolve this and I could try my hand at some ruby!

**Comment by gjtorikian** [comment]
Hey, good idea! I'm not sure why this wasn't implemented before. I've just added it.
