### ISSUE TITLE
Does GitHub use this gem?

### ISSUE THREAD

**Issue by veeral-patel** [gjtorikian/graphql-docs#77]
Just curious, does GitHub use this gem to generate their GraphQL API reference?

https://developer.github.com/v4

**Comment by gjtorikian** [comment]
Yes. I built that site, and the tooling.

**Comment by veeral-patel** [comment]
@gjtorikian I was actually looking for a project that would generate a documentation site like GitHub’s, and stumbled upon this project!

Thanks a lot for open sourcing this tool! Any tips or gotchas when replacing the existing SCSS with my own?

**Comment by gjtorikian** [comment]
I think the only thing that comes to mind--one thing people don't realize--is that you can pass in your own HTML template. 

For example, [here is the generic default](https://github.com/gjtorikian/graphql-docs/blob/56cba3a11e6854687a393073811c639e32f65a31/lib/graphql-docs/layouts/graphql_objects.html) format for an object. But this is a configuration option, [and you can just provide your own path](https://github.com/gjtorikian/graphql-docs/blob/56cba3a11e6854687a393073811c639e32f65a31/lib/graphql-docs/configuration.rb#L33) to a template to make use of.

I probably should at least update the default SCSS to make it look a little nicer. The current demo site is a little blech...

**Comment by veeral-patel** [comment]
@gjtorikian Nice! I would add this to the README. I saw the template files when reading the source code but I don't think a casual viewer of the repo would know this is supported!
