### ISSUE TITLE
Parser will throw an exception when schema does not have mutation object types 

### ISSUE THREAD

**Issue by michal-samluk** [gjtorikian/graphql-docs#8]
I currently have schema without any mutations. Line 28 here will throw an exception when generating docs. 
https://github.com/gjtorikian/graphql-docs/blob/master/lib/graphql-docs/parser.rb#L26-L28

```
NoMethodError: undefined method `[]' for nil:NilClass
	from /usr/local/bundle/gems/graphql-docs-0.1.1/lib/graphql-docs/parser.rb:28:in `parse'
```

**Comment by gjtorikian** [comment]
Thanks! Sorry!
